version: '3'
services:
  db:
    image: postgres:14  # Use uma imagem oficial do PostgreSQL
    environment:
      POSTGRES_DB: hackdb  # Nome do banco de dados
      POSTGRES_USER: hackuser  # Nome de usuário do banco de dados
      POSTGRES_PASSWORD: hackpass  # Senha do banco de dados
    ports:
      - "5432:5432"  # Mapeie a porta do PostgreSQL do contêiner para a porta do host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U hackuser -d hackdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile  # Nome do seu Dockerfile de desenvolvimento
    ports:
      - "8000:8000"  # Mapeamento da porta do contêiner para a porta do host
    volumes:
      - .:/app  # Mapeamento do diretório local para o diretório de trabalho no contêiner
    environment:
      POSTGRES_DB_NAME: hackdb  # Nome do banco de dados
      POSTGRES_DB_USER: hackuser  # Nome de usuário do banco de dados
      POSTGRES_DB_PASSWORD: hackpass  # Senha do banco de dados
      POSTGRES_DB_HOST: db  # Host do banco de dados
      POSTGRES_DB_PORT: 5432  # Porta do banco de dados
      SECRET_KEY: "secret_key:diansidjmapsodkmaplsmdlpas"
      TESTING: 0
    depends_on:
      db:  # Aguarde o serviço do banco de dados PostgreSQL
        condition: service_healthy
