# Generated by Django 5.0.7 on 2024-07-22 21:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('endereco', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='especialidades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duracao', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.perfilusuario')),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.clinica'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('pendente', 'Pendente')], default='pendente', max_length=20, null=True)),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.agenda')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='hackathon.perfilusuario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='hackathon.perfilusuario')),
            ],
        ),
    ]
