# Generated by Django 5.0.7 on 2024-07-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_clinica_perfilusuario_especialidades_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
