apiVersion: v1
kind: Service
metadata:
  name: hack-svc
  labels:
    app: hack-app
    service: hack-app
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: hack-app
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hack
  labels:
    account: hack
